# Generated by Django 5.1.5 on 2025-03-04 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Manchado', 'Manchado')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(db_column='F200_ID', max_length=50)),
                ('nombre', models.CharField(db_column='f200_razon_social', max_length=50)),
                ('cargo', models.CharField(db_column='C0763_DESCRIPCION', max_length=50)),
            ],
            options={
                'db_table': 'BI_W0550',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boomper_delantero', models.ManyToManyField(related_name='boomper_delantero', to='CarroTaller.estadoparte')),
                ('boomper_trasero_tapamaleta', models.ManyToManyField(related_name='boomper_trasero_tapamaleta', to='CarroTaller.estadoparte')),
                ('faldon_trasero_derecho', models.ManyToManyField(related_name='faldon_trasero_derecho', to='CarroTaller.estadoparte')),
                ('faldon_trasero_izquierdo', models.ManyToManyField(related_name='faldon_trasero_izquierdo', to='CarroTaller.estadoparte')),
                ('llanta_delantera_derecha', models.ManyToManyField(related_name='llanta_delantera_derecha', to='CarroTaller.estadoparte')),
                ('llanta_delantera_izquierda', models.ManyToManyField(related_name='llanta_delantera_izquierda', to='CarroTaller.estadoparte')),
                ('llanta_trasera_derecha', models.ManyToManyField(related_name='llanta_trasera_derecha', to='CarroTaller.estadoparte')),
                ('llanta_trasera_izquierda', models.ManyToManyField(related_name='llanta_trasera_izquierda', to='CarroTaller.estadoparte')),
                ('puerta_faldon_delantero_conductor', models.ManyToManyField(related_name='puerta_faldon_delantero_conductor', to='CarroTaller.estadoparte')),
                ('puerta_faldon_delantero_copiloto', models.ManyToManyField(related_name='puerta_faldon_delantero_copiloto', to='CarroTaller.estadoparte')),
                ('puerta_trasera_conductor', models.ManyToManyField(related_name='puerta_trasera_conductor', to='CarroTaller.estadoparte')),
                ('puerta_trasera_copiloto', models.ManyToManyField(related_name='puerta_trasera_copiloto', to='CarroTaller.estadoparte')),
                ('techo_capot', models.ManyToManyField(related_name='techo_capot', to='CarroTaller.estadoparte')),
            ],
            options={
                'db_table': 'detallecarro',
            },
        ),
        migrations.CreateModel(
            name='FotoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parte', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='fotosDetalle/')),
                ('detalle_carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='CarroTaller.detallecarro')),
            ],
            options={
                'db_table': 'fotosdetalle',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_operador', models.CharField(max_length=25)),
                ('codigo_operador', models.CharField(max_length=50)),
                ('nombre_operador', models.CharField(max_length=50)),
                ('cedula_acompanante', models.CharField(max_length=25)),
                ('nombre_acompanante', models.CharField(max_length=50)),
                ('cargo_acompanante', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('hora_entrada', models.TimeField()),
                ('motivo_salida', models.CharField(max_length=30)),
                ('autorizacion', models.CharField(max_length=50)),
                ('observaciones', models.CharField(default='Ninguna', max_length=100)),
                ('estado_registro', models.IntegerField(default=1)),
                ('ultimo_vigilante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ultimo_vigilante', to=settings.AUTH_USER_MODEL)),
                ('vigilante_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_vigilante_asignado_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registros',
            },
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='registro_carro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarroTaller.registro'),
        ),
    ]
