# Generated by Django 5.1.5 on 2025-03-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarroTaller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallecarro',
            name='llanta_trasera_derecha',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='boomper_delantero',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='puerta_trasera_conductor',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='puerta_trasera_copiloto',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='llanta_trasera_izquierda',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='puerta_faldon_delantero_conductor',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='techo_capot',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='llanta_delantera_izquierda',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='faldon_trasero_derecho',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='llanta_delantera_derecha',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='faldon_trasero_izquierdo',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='puerta_faldon_delantero_copiloto',
        ),
        migrations.RemoveField(
            model_name='detallecarro',
            name='boomper_trasero_tapamaleta',
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='llanta_trasera_derecha',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='boomper_delantero',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='puerta_trasera_conductor',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='puerta_trasera_copiloto',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='llanta_trasera_izquierda',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='puerta_faldon_delantero_conductor',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='techo_capot',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='llanta_delantera_izquierda',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='faldon_trasero_derecho',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='llanta_delantera_derecha',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='faldon_trasero_izquierdo',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='puerta_faldon_delantero_copiloto',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
        migrations.DeleteModel(
            name='EstadoParte',
        ),
        migrations.AddField(
            model_name='detallecarro',
            name='boomper_trasero_tapamaleta',
            field=models.CharField(choices=[('Rayón', 'Rayón'), ('Fisura', 'Fisura'), ('Ninguna', 'Ninguna'), ('Manchado', 'Manchado')], default='Ninguna', max_length=20),
        ),
    ]
